Fix Annotations
adafruit/Adafruit_CircuitPython_SGP40 pull request #17
Opened 2022-12-13 18:31 UTC by tcfranks

resolves #11 
submitted for review / comment

2023-01-06 00:09 UTC, tekktrik requested changes
This one's a little bit more complex in the `voc_algorithm.py` file, so here's feedback for part 1 while I look at that next.

2023-01-15 14:49 UTC, tcfranks commented on adafruit_sgp40/__init__.py
> +        self, temperature: float = 25, relative_humidity: float = 50
@tekktrik I don't understand.  Isn't that what I put in the updae?

2023-01-15 19:01 UTC, tekktrik commented on adafruit_sgp40/__init__.py
> +        self, temperature: float = 25, relative_humidity: float = 50
Weird, it is, I guess I was looking at the wrong thing?  In any case, resolved!

2023-01-15 22:34 UTC, tcfranks commented
resubmitted __init__.py with suggested change

2023-01-16 01:35 UTC, tekktrik approved these changes
Thanks!

2023-01-16 01:35 UTC, merged